name: execute linters and tests
on: pull_request 

jobs:
  ci: 
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "Hello World"
        

  ci2:
    runs-on: ubuntu-latest
    steps:
      - name: step2
        run: echo "Hello World2"
