name: execute linters and tests
on: pull_request 

jobs:
  ci: 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lweng/backend

    steps:
      - name: Run linter on backend
        run: npm run lint
        

  ci2:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lweng/frontend

    steps:
      - name: Run linter on frontend
        run: npm run lint
